function [fitresult, gof] = createFit(EMG_amplitude_modulated, IAP)
%CREATEFIT(EMG_AMPLITUDE_MODULATED,IAP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : EMG_amplitude_modulated
%      Y Output: IAP
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Mar-2023 22:30:12


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( EMG_amplitude_modulated, IAP );

% Set up fittype and options.
ft = fittype( '280*exp(-((x-b)/c)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [89.8912 24];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'IAP vs. EMG_amplitude_modulated', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'EMG_amplitude_modulated', 'Interpreter', 'none' );
ylabel( 'IAP', 'Interpreter', 'none' );
grid on


